# Generated by Django 3.2.3 on 2021-07-14 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('no', 'No Disease'), ('gp', 'Germline Pathogenicity'), ('so', 'Somatic Oncogenicity')], default='no', max_length=2)),
                ('func_sig', models.CharField(blank=True, choices=[(None, 'Select'), ('Established', 'Established Significance'), ('Likely', 'Likely Significance'), ('Predicted', 'Predicted/Possible Significance'), ('VUS', 'Uncertain Significance'), ('Benign', 'Benign')], max_length=20, null=True, verbose_name='Functional Significance')),
                ('others', models.CharField(blank=True, choices=[(None, 'Select'), ('Tier I', 'Tier I'), ('Tier II', 'Tier II'), ('Tier III', 'Tier III'), ('Tier IV', 'Tier IV')], max_length=20, null=True, verbose_name='Tier')),
                ('report', models.TextField(blank=True, default='', max_length=255, verbose_name='Germline Report')),
                ('reviewed', models.CharField(choices=[('n', 'Not Reviewed'), ('r', 'Reviewed'), ('m', 'Secondly Reviewed'), ('a', 'Approved')], default='n', max_length=1)),
                ('curation_notes', models.TextField(blank=True, default='', max_length=255, verbose_name='Curation Notes'))
            ],
            options={
                'ordering': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, default='', max_length=75, verbose_name='Functional Category')),
                ('source_type', models.CharField(choices=[(None, 'Select'), ('PM', 'PMID'), ('O', 'Others')], max_length=2)),
                ('source_id', models.CharField(blank=True, default='', max_length=20)),
                ('statement', models.TextField(blank=True, default='', null=True)),
                ('evid_sig', models.CharField(blank=True, choices=[(None, 'Select'), ('Pred', 'Predictive'), ('Prog', 'Prognostic'), ('Diag', 'Diagnostic')], max_length=4, null=True, verbose_name='Evidence Significance')),
                ('level', models.CharField(blank=True, choices=[(None, 'Select'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True, verbose_name='Evidence Level')),
                ('evid_dir', models.BooleanField(blank=True, choices=[(None, 'Select'), (True, 'Support'), (False, 'Does Not Support')], null=True, verbose_name='Evidence Direction')),
                ('clin_sig', models.CharField(blank=True, choices=[(None, 'Select'), ('Pred: Resistance', 'Pred: Resistance'), ('Pred: Adverse Response', 'Pred: Adverse Response'), ('Pred: Reduced Sensitivity', 'Pred: Reduced Sensitivity'), ('Pred: Sensitivity', 'Pred: Sensitivity'), ('Prog: Better Outcome', 'Prog: Better Outcome'), ('Prog: Poorer Outcome', 'Prog: Poorer Outcome'), ('Dx: Positive Diagnosis', 'Dx: Positive Diagnosis'), ('Dx: Negative Diagnosis', 'Dx: Negative Diagnosis')], max_length=25, null=True, verbose_name='Clinical Significance')),
                ('drug_class', models.TextField(blank=True, null=True, verbose_name='Drug/Drug Class/Dx')),
                ('evid_rating', models.IntegerField(blank=True, choices=[(0, 'Select'), (1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True, verbose_name='Evidence Rating')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='api.disease')),
            ],
            options={
                'ordering': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('content', models.TextField(blank=True, null=True)),
                ('germline_content', models.TextField(blank=True, null=True)),
                ('actionable', models.CharField(blank=True, null=True, max_length=50, verbose_name='Actionable In')),
                ('not_actionable', models.CharField(blank=True, null=True, max_length=50, verbose_name='Not Actionable In')),
                ('mut_type', models.CharField(blank=True, null=True, max_length=50, verbose_name='Actionable Mutation Types')),
                ('region', models.CharField(blank=True, null=True, max_length=50, verbose_name='Actionable Regions')),
                ('reviewed_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Reviewed Date')),
                ('gene_curation_notes', models.TextField(blank=True, default='', max_length=255, verbose_name='Gene Curation Notes')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdna', models.CharField(default='', max_length=20, verbose_name='c.')),
                ('protein', models.CharField(max_length=20, unique=True, verbose_name='p.')),
                ('chr', models.CharField(default='', max_length=6, verbose_name='Chromosome')),
                ('transcript', models.CharField(max_length=20)),
                ('start', models.CharField(default='', max_length=10)),
                ('end', models.CharField(default='', max_length=10)),
                ('ref', models.CharField(default='', max_length=100)),
                ('alt', models.CharField(default='', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Curation Notes')),
                ('germline_content', models.TextField(blank=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.gene')),
            ],
            options={
                'ordering': ['protein'],
            },
        ),
        migrations.CreateModel(
            name='VariantField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='field name')),
                ('value', models.CharField(default='', max_length=500)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.variant')),
            ],
            options={
                'ordering': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_score', models.CharField(default='Uncertain', max_length=20, verbose_name='For Pathogenicity')),
                ('against_score', models.CharField(default='Uncertain', max_length=20, verbose_name='Against Pathogenicity')),
                ('content', models.CharField(default='Uncertain', max_length=100, verbose_name='ACMG Classification')),
                ('disease', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='api.disease')),
            ],
            options={
                'ordering': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(choices=[('n', 'Not Reviewed'), ('r', 'Reviewed'), ('m', 'Secondly Reviewed'), ('a', 'Approved')], max_length=1)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.disease')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=40)),
                ('content', models.TextField(blank=True, null=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.disease')),
                ('gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.gene')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.variant')),
            ],
            options={
                'ordering': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='api.evidence', verbose_name='field')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.variant')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='api.variant'),
        ),
        migrations.CreateModel(
            name='CancerHotspot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot', models.CharField(default='', max_length=70)),
                ('count', models.IntegerField(default=1)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='api.variant')),
            ],
            options={
                'ordering': [],
                'abstract': False,
            },
        ),
    ]
